### ISSUE TITLE
IE 환경에서 innerWidth에 따라 post가 사라짐

### ISSUE THREAD

**Issue by bactoria** [bactoria/ToyProject-Blog-Nuxt#7]
1px 단위로 보였다가 안보였다가 함.

가끔 2px마다 그러는 부분도 있고..

원인은 아직 모르겠음.

**Comment by bactoria** [comment]
ssr인데 vw 계산이 꼬이나?
근데 크롬에서는 잘되는데..

일단 해결은 함.

```css
# 기존 코드
    width: calc(100% - #{$left-menu-width});
    float: right;
```

```css
# 이슈 해결됨
    width: calc(100vw - #{$left-menu-width});
    
    position: relative;
    left: 20vw;
```

```css
# 이슈 해결안됨
    width: calc(100% - #{$left-menu-width});
    
    position: relative;
    left: 20vw;
```
